### ISSUE TITLE
After upgrade to pfsense 2.4 i get errors

### ISSUE THREAD

**Issue by filipvh** [PiBa-NL/pfsense-haproxy-package-doc#1]
Hi

After an upgrade to newest pfsense, i get:
May 11 11:15:00 php-cgi     rc.filter_configure_sync: PHP ERROR: Type: 1, File: /usr/local/pkg/haproxy/haproxy.inc, Line: 436, Message: Cannot redeclare haproxy_version() (previously declared in /usr/local/pkg/haproxy.inc:427)
May 11 11:14:59 kernel      arp: 192.168.0.115 moved from 44:6d:57:34:6e:bf to e8:40:f2:d3:1b:83 on em1
May 11 11:00:01 php-cgi     rc.filter_configure_sync: PHP ERROR: Type: 1, File: /usr/local/pkg/haproxy/haproxy.inc, Line: 436, Message: Cannot redeclare haproxy_version() (previously declared in /usr/local/pkg/haproxy.inc:427)
May 11 10:58:35 php-cgi     config.inc: PHP ERROR: Type: 1, File: /usr/local/pkg/haproxy_utils.inc, Line: 164, Message: Call to undefined function get_configured_carp_interface_list()

**Comment by PiBa-NL** [comment]
I assume you mean pfSense 2.3 :)
Its a known issue: https://redmine.pfsense.org/issues/6137
Solution is to remove the old files, and then reinstall the package: https://forum.pfsense.org/index.php?topic=109783.msg611641#msg611641

Can you confirm&close this issue if that indeed fixes it.?

**Comment by filipvh** [comment]
Doesn't this remove my whole haproxy setup?

2016-05-11 19:42 GMT+02:00 PiBa-NL <notifications@github.com>:

**Comment by filipvh** [comment]
`find / \( -name "haproxy*.inc" -o -name "haproxy*.php" \) -exec rm -rf {} \;`

fixed it :)

**Comment by PiBa-NL** [comment]
Ok great, config is kept as before as that is stored in config.xml. Closing :)
