### ISSUE TITLE
 HAproxy multi-wan 

### ISSUE THREAD

**Issue by wesleylc1** [PiBa-NL/pfsense-haproxy-package-doc#12]
Hey, @PiBa-NL 

I hope everyone is okay!

I have a multi-wan HAproxy environment, with different incoming SIP traffic, responding on two front ends on ports 80 and 443, in which traffic is successfully directed to all back ends.

But my problem starts now, at the moment when I need to add a third front-end, a new ISP for HAProxy, and direct traffic from a Backend to this new WAN-ip.

Here I can explain in more detail the steps taken in the settings:

- Performed the configuration of the new wap-ip interface, using the settings provided by my provider:

![01](https://user-images.githubusercontent.com/29066796/91743809-c7e86100-eb8e-11ea-8ca2-08ca3970aa8e.png)

![02](https://user-images.githubusercontent.com/29066796/91743823-cf0f6f00-eb8e-11ea-8d98-e21bb2b46860.png)

- I made a new backend with a new wap-ip interface

![03](https://user-images.githubusercontent.com/29066796/91743874-e9494d00-eb8e-11ea-8fab-30b1029eb6a1.png)

Finally, I published the new wan-ip address in the external DNS, but the web server is not accessible.

![04](https://user-images.githubusercontent.com/29066796/91743907-f8c89600-eb8e-11ea-8ce2-ac2e8f5aca61.png)

With kind regards!

**Comment by PiBa-NL** [comment]
Really should be asking this question on the pfSense forum.. But anyhow.. did you spot the difference?:
![image](https://user-images.githubusercontent.com/2302892/91748490-59bc9200-ebc0-11ea-9f2e-969a287f0430.png)

**Comment by wesleylc1** [comment]
I'm sorry for posting this content here on GitHub !!
I posted the problem on the pfsense forum, but I haven't had help there yet.

I'm so sorry.

After adjusting the frontend, according to your observation, it works, but I still have problems accessing the web server externally. It does not access via smartphone (Firefox / Chrome), unless the https protocol is indicated (https: / /nextcloud.projectus.com.br), and on desktops it is necessary to indicate https: // only when connected by Google Chrome.

note:
The problem does not occur when connecting using the wan-ip interface that was previously configured, this problem only occurs when publishing to connect via the new ISP.

![Captura de tela de 2020-08-31 15-20-16](https://user-images.githubusercontent.com/29066796/91754847-82cd2a80-eba0-11ea-8067-30517a7f630c.png)
