### ISSUE TITLE
Port range in frontend

### ISSUE THREAD

**Issue by mathieuchateau** [PiBa-NL/pfsense-haproxy-package-doc#13]
Hello,

I can't figure how to configure a port range in haproxy.
Version:
Pfsense 2.4.5
haproxy 1.8.25
package 0.60_6

When I try to set a port range instead of 1 port on Frontend, I have this error message:
The external address field 'Port' value '30000-40000' is not a number or alias thereof.
I also try with syntax 30000:40000

I can set nothing, so I guess it will take all ports, but that's bad. Looks like using port range is possible from a long time in haproxy.

This is to set up an FTP service with nodes.

Thanks in avance for your help

**Comment by PiBa-NL** [comment]
Did you read the message and try what it implies? "or alias thereof."

You can create a firewall/alias:
![image](https://user-images.githubusercontent.com/2302892/100476193-43ea3a80-30e5-11eb-8b04-a6eb042af816.png)
And then use that in haproxy:
![image](https://user-images.githubusercontent.com/2302892/100476232-56647400-30e5-11eb-991f-22eedcfb2b74.png)
Which it will then bind to:
![image](https://user-images.githubusercontent.com/2302892/100476299-7c8a1400-30e5-11eb-8d0d-32595deb960f.png)

**Comment by mathieuchateau** [comment]
Hello,

Thanks for helping. I did see it, but thought it was for well known port, like smtp instead of port 25.
I thought it could also be what you show, but it looked too far stretched.
Great it works using Pfsense alias port. Maybe just enhance the sentence to more explicit, like "Pfsence port alias" ?

**Comment by PiBa-NL** [comment]
I guess reading the sentence again it indeed seems to say that you could perhaps write 'smtp' as a alias for the port '25' for a single port.. And does not so much refer to 'pfSense port aliases' or portranges specifically.. Ill try and remember to change that text a little with a next update.. :) Or perhaps even allow manually putting in port ranges..
