### ISSUE TITLE
Haproxy get 503 on https

### ISSUE THREAD

**Issue by x0139** [PiBa-NL/pfsense-haproxy-package-doc#4]
Hello everyone!
I have a stange situation - i setup a Haproxy like a frontend with 1 external ip-address with multiply backend hosts, on 2 ports - 80 for http and 443 for https.
All works fine, except one host - this host does not work on https, get "503 Service Unavailable", NOSRV in logs.
It works perfect via http, and this backend host has GREEN status in STATS FS.
But dont work on https....
Why?

**Comment by x0139** [comment]
Very strange situation - i add one more frontend reverse proxy and wrote same  acl on it - and all work...
seems like this is bug in haproxy...

**Comment by PiBa-NL** [comment]
Lets discus on the duplicate topic: https://forum.pfsense.org/index.php?topic=120608.0
