### ISSUE TITLE
Haproxy on second node lost connection and all properties

### ISSUE THREAD

**Issue by x0139** [PiBa-NL/pfsense-haproxy-package-doc#5]
Hello!
I use pfSense community edition v. 2.3.2-RELEASE-p1  and Haproxy-devel package.
Setup a 2-cluster nodes with XMLRPC for sync haproxy config.
All work, but after creating some new backends and setuping them in frontend on main node, syncing with second node is lost and all preferences on second node dissapear and haproxy on it stop working.
After some dancing with a tambourine on second node (i.e. reinstall haproxy-devel package) haproxy start working, but if i made some changes on main node Haproxy stop working again.
Why?

**Comment by x0139** [comment]
Got this errors after haproxy stop working on node 2:

> Settings Sync
> 
> A communications error occurred while attempting Filter sync with username admin https://172.29.41.252:443.   @ 2016-11-04 09:23:04
> 
> HAProxy Settings Reload
> 
> A communications error occurred while attempting HAProxy XMLRPC sync with https://172.29.41.252:443 (exec_php).   @ 2016-11-04 09:23:10

of course i do not change the sync password
Modify message

**Comment by PiBa-NL** [comment]
Lets discuss on the duplicate forum topic: https://forum.pfsense.org/index.php?topic=120622
