### ISSUE TITLE
HAProxy 0.59_4 is broken

### ISSUE THREAD

**Issue by smoothrunnings** [PiBa-NL/pfsense-haproxy-package-doc#6]
Hi, I dont see any other way of reaching you other than through here. Please have a read through the post I created this morning on this subject on the pfsense fourms. 
https://forum.netgate.com/topic/133234/haproxy-0-59_4-is-broken

I would like to see a fix for this. Others on Reddit have confirmed its broken. 
https://www.reddit.com/r/PFSENSE/comments/92it0e/haproxy_setup_issue/

Thanks! 👍

**Comment by PiBa-NL** [comment]
Usually ill find forum posts if they mention 'haproxy'. I'm only online most evenings and weekends though. Got a dayjob as well :), so it can sometimes take a day or 2 for me to respond. Anyhow i realize this is a 'urgent' issue.. Lets continue discussion on the forum though.
