### ISSUE TITLE
ssl/https vs tcp mode is not documented

### ISSUE THREAD

**Issue by bradvido** [PiBa-NL/pfsense-haproxy-package-doc#7]
This has always confused me, what is the difference between the last two option sin the type dropdown:

> ssl / https(TCP mode)
> tcp

![image](https://user-images.githubusercontent.com/884611/46970378-82941680-d07e-11e8-90c0-461445612702.png)

I've confirm both set the `mode tcp` in the front-end config, and it's unclear what the difference is.

**Comment by PiBa-NL** [comment]
There are different SNI related acl's available in the menu below. Other than that, i cant think of much..

**Comment by bradvido** [comment]
Is there any advantage or reason to pick `tcp` only?

**Comment by PiBa-NL** [comment]
Not really.. Just when you 'know' something isn't ssl based, then SNI acl's wouldn't work anyhow. And well to call for example a SMTP connection for a balanced bunch of mailservers, calling it "ssl/https" isn't really logical either. But i did want to emphasize that 'mode tcp' can be the correct option for https based traffic. Depending of desired option for ssl-passthrough vs ssl-offloading.

**Comment by bradvido** [comment]
Thanks, this can be closes
